
name: Python package

on:
  push:
    branches:
     - main
     - 'gh-readonly-queue/main/pr-**'
    tags:
      - '*'

  merge_group:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Wheel

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python packages
        run: python -m pip install --upgrade build

      - name: build
        # Not adding PYTHONWARNINGS=error as it can trigger errors in pip itself
        # See https://github.com/pypa/pip/issues/12243
        run: python -m build

      - name: Store the packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist

  test:
    needs:
      - build

    name: Test Python ${{ matrix.python.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - { version: "3.10" }
          - { version: "3.11" }
          - { version: "3.12" }
          - { version: "3.13" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: remove code outside of wheel
        run: rm -rf mercury_engine_data_structures
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}

      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Install built wheel
        run: python -m pip install "$(ls dist/*.whl)[test]" -c requirements.txt
        shell: bash

      - name: test
        run: python -m pytest  # don't include coverage, since we've deleted the source dir

  pypi:
    runs-on: 'ubuntu-latest'
    needs:
      - test

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish 📦 to TestPyPI
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.testpypi_password }}
          repository-url: https://test.pypi.org/legacy/

      - name: Create GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: "New release"

      - name: Publish 📦 to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}

  full_test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Create venv
        run: python -m venv venv

      - name: Install Python packages
        run: venv/bin/python -m pip install --upgrade pip pytest-xdist

      - name: install built wheel
        run: venv/bin/python -m pip install -e ".[test]" -c requirements.txt

      - name: Run Tests
        run:
          venv/bin/python -m pytest --cov mercury_engine_data_structures --cov-report=xml --fail-if-missing --durations=100 -n 8

      - name: codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
